### ISSUE TITLE
Compute the space requirement.

### ISSUE THREAD

**Issue by kashishbest** [IEEECS-VIT/GPL#23]
As per last year's stats, a single matchday collection took up 60 MB of data, please verify that.

**Comment by saurabhmathur96** [comment]
assigned by mistake

**Comment by kashishbest** [comment]
Assuming you ran the simulation on the gravitaspremierleague db, the results can be  misleading, half the teams are not set. Create dummy records, say 1000 records, with all teams and squads set, and then please run the simulation, and get back to me.

Btw the current size is approx 400kb for 4 matches.
