### ISSUE TITLE
Invite Every Developer to the Meeting

### ISSUE THREAD

**Issue by kashishbest** [IEEECS-VIT/GPL#24]
Add everyone to the calendar invite and drop in a message at the whatsapp group to ask people to join the meeting if possible

**Comment by ayushagarwal95** [comment]
The 3 most active developers are out of town. They should be returning by next week.

**Comment by kashishbest** [comment]
Then in that case, let us postpose the meeting to 2 weeks from now, or next weekend (for which I would not be available) You guys take a call
