### ISSUE TITLE
Admin panel

### ISSUE THREAD

**Issue by kunagpal** [IEEECS-VIT/GPL#28]
At present, the matches are simulated via the Heroku panel. A proper administrator interface with features like team count, match simulation buttons, and daily report divisions is needed.

**Comment by aneesh-neelam** [comment]
You'll need two processes for this. A Web process that hosts the admin panel (can be the rest of the website along with it) and a worker process that runs the simulations whenever asked to. 

Use [CloudAMQP](https://www.cloudamqp.com/) for communication between web and worker processes. 
@ayushagarwal95: You know how to do this, we have an identical system for [VITacademics](https://github.com/aneesh-neelam/VITacademics).
