### ISSUE TITLE
Social login

### ISSUE THREAD

**Issue by kunagpal** [IEEECS-VIT/GPL#34]
Modules need to be created for social login into GPL (Facebook, Twitter, Google, and GitHub)

**Comment by aneesh-neelam** [comment]
Just put Facebook and Google.

**Comment by kunagpal** [comment]
Any particular reason for omitting the latter half?

**Comment by aneesh-neelam** [comment]
You can put Twitter, but GitHub sign-in is for a specific developer purpose, not for social purposes.
