### ISSUE TITLE
Pipelines

### ISSUE THREAD

**Issue by kunagpal** [IEEECS-VIT/GPL#52]
In order to make seamless shifts from dev staging to production, separate apps for production and testing can be dropped in favour of one cumulative Heroku pipeline.

https://devcenter.heroku.com/articles/pipelines

**Comment by aneesh-neelam** [comment]
Pipelines do use multiple apps. It's just that they are linked. 

![Screenshot](https://dl.pushbulletusercontent.com/NVfyPREvWovY24k15gOQU0Lsm6IPl2Hp/Screenshot%202015-10-10%2001.12.22.png "Screenshot")
