### ISSUE TITLE
Cookies

### ISSUE THREAD

**Issue by kunagpal** [IEEECS-VIT/GPL#54]
Frequently accessed data like the leader board and user statistics can be cookied in order to inject significant amounts of impetus into application performance, with conditional checks to ensure that the versions of the cookie contents and the matchday value (process.env.DAY) on the server match.

**Comment by aneesh-neelam** [comment]
Hey, don't do crap like this. Cookies are supposed to have identifying and tracking information only.

**Comment by kashishbest** [comment]
Maintain a cache on the server, the application performance would be same, if a db call is not made, however a mongodb call, would not make much of a difference. rather than the cookie. Cookie can be corrupted, and fucked around with.
